####
#### SIT CD
####  

name: SIT CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, edited, review_requested, closed]
  workflow_dispatch:

jobs:
  
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      SolutionName: SIT.BetterAudioPatch                         
      CSProj: SIT.BetterAudioPatch.csproj                 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

     # Restore all projects
    - name: dotnet Restore
      run: dotnet restore

    # Build the Library
    - name: dotnet Build
      run: |
        mkdir ${{ env.SolutionName }}
        dotnet build ${{ env.CSProj }} -c ${{ matrix.configuration }}

    - name: Remove unnecessary files
      run: |
          del ${{ env.SolutionName }}-${{ matrix.configuration }}\StayInTarkov.pdb

    - name: Zip remaining files
      run: |
          Compress-Archive -Path ${{ env.SolutionName }}-${{ matrix.configuration }} -DestinationPath ${{ env.SolutionName }}-${{ matrix.configuration }}.zip

    # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: StayInTarkov-Build-${{ matrix.configuration }}
        path: ${{ env.SolutionName }}-${{ matrix.configuration }}\
        if-no-files-found: error
    
    - name: Set build date
      run: |
        $NOW=& Get-Date -format yyyy-MM-dd-HH-mm
        echo "NOW=$NOW" >> $env:GITHUB_ENV
        
    # Create release from the compressed file if pushed to master
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: (${{ matrix.configuration }} == 'Release')
      with:
        draft: true
        generate_release_notes: true
        files: ${{ env.SolutionName }}-${{ matrix.configuration }}.zip
        tag_name: SIT.BetterAudio-${{ env.NOW }}

