####
#### SIT CI
####  

name: SIT CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, edited, review_requested, closed]
  workflow_dispatch:

jobs:
  
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      SolutionName: SIT.BetterAudioPatch                         
      CSProj: SIT.BetterAudioPatch.csproj                 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

     # Restore all projects
    - name: dotnet Restore
      run: dotnet restore

    # Build the Library
    - name: dotnet Build
      run: |
        mkdir ${{ env.SolutionName }}
        dotnet build ${{ env.CSProj }} -c Release